### ISSUE TITLE
OCR not working on this world

### ISSUE THREAD

**Issue by juanpedroo** [Maxinger15/PokemonRumbleRushBot#2]
![OCR](https://i.imgur.com/hIMq8vF.png)

this is the lscreens picture
stay at the state of Fight not finished

**Comment by Maxinger15** [comment]
Try to change the size of the image in the Player.py in the method check_string. The first 2 values of the area variable are coordinates of the left top corner. Change the second value (840) to 940 or 740. I think you have to try some sizes. Does it work sometimes? How often get it stuck?

**Comment by juanpedroo** [comment]
i will try these new values tomorrow but mine are working in the cave and beach sprite 

EDIT: Now it works 1 time out of 10. I think this is related to the transparency of the text on the light background. I tried with different values for area.
Here they are now: (50, 940, 1078, 2018)
![](https://i.imgur.com/kKeZHfJ.png)

EDIT2: Not working on the beach too, the text seems to be transparent while in the cave no.

**Comment by Maxinger15** [comment]
I have made changes with this in the development branch. You can try it. I will test it later too.
The background will now be changed to red and Letters to black.
