### ISSUE TITLE
selected_raid always go for the third one

### ISSUE THREAD

**Issue by victorsevero** [Maxinger15/PokemonRumbleRushBot#3]
I don't know if this is related to any library version I may have, but this part of the code
`        if self.settings.selected_raid == "1":
            device.shell("input tap 220 1020")
`
`
        elif self.settings.selected_raid == "2":
            device.shell("input tap 220 1120")
`
`
        else:
            device.shell("input tap 220 1220")`
always goes to the else statement, because selected_raid is a string, so it doesn't matter if I changed it to 1 or 2 in config.cfg. Of course, this is extremely easy to fix.

**Comment by Maxinger15** [comment]
I fixed it. Thank you for your help :)
