### ISSUE TITLE
Crashing on Round End

### ISSUE THREAD

**Issue by wife** [Maxinger15/PokemonRumbleRushBot#7]
**Describe the bug**
Bot Crashes when the round ends and goes back to start screen or ore refining screen

**Screenshots**

**Versions: (please complete the following information):**
 - OS: Android 9.0
 - Version: Most recent

**Additional context**
https://share.g0d.org/i/uvky51.png image of error

**Comment by Maxinger15** [comment]
Fixed with the new language.json
